### ISSUE TITLE
links don't work

### ISSUE THREAD

**Issue by cobismith** [okfn/goodtables#52]
Good Tables is a great idea :)
I tested it using a CSV link from my GitHub:
https://raw.githubusercontent.com/cobismith/intlaw/master/forestlawdata.csv
Nice report design, satisfying praise for having valid data :)
When I click the buttons below 'Let others share in your success!' it takes me here, which doesn't work:

JSON link:
http://127.0.0.1:5000/api/run?data=https%3A%2F%2Fraw.githubusercontent.com%2Fcobismith%2Fintlaw%2Fmaster%2Fforestlawdata.csv&row_limit=20000&format=csv&fail_fast=True&report_limit=1000

http://127.0.0.1:5000/reports?data=https%3A%2F%2Fraw.githubusercontent.com%2Fcobismith%2Fintlaw%2Fmaster%2Fforestlawdata.csv&row_limit=20000&format=csv&fail_fast=True&report_limit=1000

**Comment by pwalsh** [comment]
Ah, thanks. That must have crept in recently. I'm doing a round of bug fixes in the coming days, and I'll fix this.

**Comment by pwalsh** [comment]
@cobismith this has been fixed.
